spring:
  application:
    name: pengapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "数据库地址"
    username: 账号
    password: 密码

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://服务器内网地址:8848
  config-center:
    timeout: 40000

server:
  address: 0.0.0.0
  port: 7529
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        domain: 服务器外网地址
